### ISSUE TITLE
Admin menu doesn't show up

### ISSUE THREAD

**Issue by netdelight** [karliuka/m2.ProductAvailable#1]
Hello,
I've ran the following command : 
```
composer require faonni/module-product-available
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy
```

But I'm not able to see the "Available" menu in Magento admin. From the screencap, I assume it should be in Stores > Configuration > General. Is that correct ?

Edit : I've finally found it : Stores > Configuration > Catalog ("Available" is the last menu), might be usefull to add it in the documentation ;-)

**Comment by karliuka** [comment]
Thank you) You are right, the documentation needs to be added.
