### ISSUE TITLE
Products show as out of stock

### ISSUE THREAD

**Issue by beltoftandersen** [karliuka/m2.ProductAvailable#11]
Prices and add to cart are hidden for guests, but all products show as out of stock for guests

**Comment by kanenas** [comment]
@karliuka I can confirm that in my Magento v.2.3.x installation all products show as out of stock for guests. Is there some setting or something that we should do?

**Comment by karliuka** [comment]
All settings are Stores > Configuration > Catalog > Product Available.

**Comment by kanenas** [comment]
@karliuka in my Magento v.2.3.1 installation here https://imgur.com/a/h3cOJVQ is `Stores > Configuration > Catalog > Product Available`
