### ISSUE TITLE
Possible for replacement text?

### ISSUE THREAD

**Issue by ne0nlight** [karliuka/m2.ProductAvailable#3]
When hiding the Add to Cart, it simply removes the quantity and add to cart button, is it possible to also place something like 'Log in for pricing' in place of the empty area?

**Comment by karliuka** [comment]
it possible
see file vendor/magento/module-catalog/view/frontend/templates/product/view/addtocart.phtml method $_product->isSaleable()

**Comment by ne0nlight** [comment]
Perfect! Thank you!
