### ISSUE TITLE
Compatibility with 2.3?

### ISSUE THREAD

**Issue by epiblue** [karliuka/m2.ProductAvailable#6]
On the front end it works as expected, 

When I install it I get this on the default theme and fresh install with few items, in the backend Catalog section and COnfiguration section I get this:

> {"0":"Warning: Invalid argument supplied for foreach() in \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/app\/code\/Magento\/Config\/Model\/Config\/Structure\/Mapper\/Sorting.php on line 38","1":"#0 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/app\/code\/Magento\/Config\/Model\/Config\/Structure\/Mapper\/Sorting.php(38): Magento\\Framework\\App\\ErrorHandler->handler(2, 'Invalid argumen...', '\/home\/admin\/web...', 38, Array)\n#1 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/app\/code\/Magento\/Config\/Model\/Config\/Structure\/Mapper\/Sorting.php(27): Magento\\Config\\Model\\Config\\Structure\\Mapper\\Sorting->_processConfig('\\t\\t\\n    ')\n#2 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/app\/code\/Magento\/Config\/Model\/Config\/Structure\/Converter.php(68): Magento\\Config\\Model\\Config\\Structure\\Mapper\\Sorting->map(Array)\n#3 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(58): Magento\\Config\\Model\\Config\\Structure\\Converter->convert(Object(DOMDocument))\n#4 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(138): Magento\\Config\\Model\\Config\\Structure\\Converter\\Interceptor->___callParent('convert', Array)\n#5 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Config\\Model\\Config\\Structure\\Converter\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(DOMDocument))\n#6 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/generated\/code\/Magento\/Config\/Model\/Config\/Structure\/Converter\/Interceptor.php(26): Magento\\Config\\Model\\Config\\Structure\\Converter\\Interceptor->___callPlugins('convert', Array, Array)\n#7 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/app\/code\/Magento\/Config\/Model\/Config\/Structure\/Reader.php(121): Magento\\Config\\Model\\Config\\Structure\\Converter\\Interceptor->convert(Object(DOMDocument))\n#8 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/Config\/Reader\/Filesystem.php(132): Magento\\Config\\Model\\Config\\Structure\\Reader->_readFiles(Object(Magento\\Framework\\Config\\FileIterator))\n#9 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/Config\/Data\/Scoped.php(119): Magento\\Framework\\Config\\Reader\\Filesystem->read('adminhtml')\n#10 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/Config\/Data\/Scoped.php(97): Magento\\Framework\\Config\\Data\\Scoped->_loadScopedData()\n#11 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/app\/code\/Magento\/Config\/Model\/Config\/Structure.php(127): Magento\\Framework\\Config\\Data\\Scoped->get()\n#12 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/generated\/code\/Magento\/Config\/Model\/Config\/Structure\/Interceptor.php(14): Magento\\Config\\Model\\Config\\Structure->__construct(Object(Magento\\Config\\Model\\Config\\Structure\\Data), Object(Magento\\Config\\Model\\Config\\Structure\\Element\\Iterator\\Tab), Object(Magento\\Config\\Model\\Config\\Structure\\Element\\FlyweightFactory), Object(Magento\\Config\\Model\\Config\\ScopeDefiner))\n#13 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/ObjectManager\/Factory\/AbstractFactory.php(116): Magento\\Config\\Model\\Config\\Structure\\Interceptor->__construct(Object(Magento\\Config\\Model\\Config\\Structure\\Data), Object(Magento\\Config\\Model\\Config\\Structure\\Element\\Iterator\\Tab), Object(Magento\\Config\\Model\\Config\\Structure\\Element\\FlyweightFactory), Object(Magento\\Config\\Model\\Config\\ScopeDefiner))\n#14 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/ObjectManager\/Factory\/Compiled.php(108): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\\\Config\\\\...', Array)\n#15 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/ObjectManager\/Factory\/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\\\Config\\\\...')\n#16 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/ObjectManager\/Factory\/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Magento\\\\Config\\\\...')\n#17 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\\\Variabl...')\n#18 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/app\/code\/Magento\/Variable\/Model\/Variable\/Config.php(61): Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\\\Variabl...')\n#19 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/ObjectManager\/Factory\/AbstractFactory.php(116): Magento\\Variable\\Model\\Variable\\Config->__construct(Object(Magento\\Framework\\View\\Asset\\Repository), Object(Magento\\Backend\\Model\\Url), NULL, NULL, NULL)\n#20 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/ObjectManager\/Factory\/Compiled.php(108): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\\\Variabl...', Array)\n#21 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/ObjectManager\/Factory\/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\\\Variabl...')\n#22 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/ObjectManager\/Factory\/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Magento\\\\Variabl...')\n#23 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/ObjectManager\/Factory\/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\\\Cms\\\\Mod...')\n#24 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/ObjectManager\/Factory\/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Magento\\\\Cms\\\\Mod...')\n#25 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/ObjectManager\/Factory\/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\\\Catalog...')\n#26 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/ObjectManager\/Factory\/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Magento\\\\Catalog...')\n#27 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/ObjectManager\/ObjectManager.php(56): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\\\Catalog...', Array)\n#28 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/App\/ActionFactory.php(44): Magento\\Framework\\ObjectManager\\ObjectManager->create('Magento\\\\Catalog...')\n#29 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/App\/Router\/Base.php(304): Magento\\Framework\\App\\ActionFactory->create('Magento\\\\Catalog...')\n#30 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/App\/Router\/Base.php(165): Magento\\Framework\\App\\Router\\Base->matchAction(Object(Magento\\Framework\\App\\Request\\Http), Array)\n#31 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/App\/FrontController.php(95): Magento\\Framework\\App\\Router\\Base->match(Object(Magento\\Framework\\App\\Request\\Http))\n#32 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#33 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#34 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#35 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, Array)\n#36 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#37 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/lib\/internal\/Magento\/Framework\/App\/Bootstrap.php(258): Magento\\Framework\\App\\Http->launch()\n#38 \/home\/admin\/web\/nanotekas.es\/public_html\/magento3\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#39 {main}","url":"\/magento3\/admin_8nr5k2\/catalog\/product\/index\/key\/f0189ad4c0f5381de694b6c25c7e95bc1fb360a9c5ec10ebf6dca246666e2767\/","script_name":"\/magento3\/index.php"}

Any ideas?

**Comment by karliuka** [comment]
Sorry, but I do not find problems in the module (frontend and backend). try to delete the generated/ folder and new compile the files (running setup:di:compile)
